### ISSUE TITLE
jgontrum/spacyapi:en_v2 | Dependency parsing failed: Can't find model 'en'

### ISSUE THREAD

**Issue by silentsnooc** [jgontrum/spacy-api-docker#12]
For some reason, the following:

```python
{
  'model': 'en', 
  'collapse_phrases': True, 
  'text': 'I paid him $100,- for nothing!', 
  'collapse_punctuation': False
}
```

Gives me 

    Dependency parsing failed: Can't find model 'en'

from the server.

I am running

    docker run -p "127.0.0.1:8082:80" jgontrum/spacyapi:en_v2

Do I have to set another model name? I already tried `en_v2`.

**Comment by jgontrum** [comment]
Ah, you're right. The reason is that in spaCy 2, the model names are more explicit. Can you try 'en_core_web_sm' as model name?

`curl --request POST \
  --url http://localhost:8082/dep/ \
  --header 'content-type: application/json' \
  --data '{
  "model": "en_core_web_sm", 
  "collapse_phrases": true, 
  "text": "I paid him $100,- for nothing!", 
  "collapse_punctuation": false
}'`

gives me a valid result.

**Comment by jgontrum** [comment]
I just updated the API to use the current stable spaCy version, so the value for model should be 'en' instead now.
