### ISSUE TITLE
POS Tree

### ISSUE THREAD

**Issue by PKuebler** [jgontrum/spacy-api-docker#5]
Would it be possible to return the POS TREE next to the token?

**Comment by jgontrum** [comment]
What exactly do you mean by "POS Tree"? In general, each token has only one part-of-speech tag.

**Comment by PKuebler** [comment]
Sorry, I meant the dependency parser.

https://spacy.io/docs/usage/dependency-parse
https://demos.explosion.ai/displacy/

as Json Tree?

	[{
		token...
		modifiers: [{
			token...
		}]
	}]

**Comment by jgontrum** [comment]
Ah yes, this is something I've also been thinking about for a while. 

Representing the dependency tree as JSON seems to be a good idea, even though I would probably use the indices of the tokens there instead of the whole object to reduce redundancy. I'll see if I have time to implement it next weekend :)

**Comment by PKuebler** [comment]
Netflix API "Falcor" returns the objects and structure separately. In the structure, they reference only the IDs of the objects.

http://netflix.github.io/falcor/documentation/jsongraph.html

**Comment by skerit** [comment]
There's a Syntaxnet docker image that gives this information by adding a "head" property to each token, pointing to that token's parent token. Very easy for the receiving endpoint to create a tree out of, or just ignore it.
